name: chimera-gate

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_review:
    types: [submitted, edited, dismissed]

concurrency:
  group: chimera-gate-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read
  statuses: write

defaults:
  run:
    shell: bash

jobs:
  gate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      HEAD_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
      PR_NUMBER: ${{ github.event.pull_request.number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: gate status → pending
        if: ${{ always() }}
        run: |
          curl --fail-with-body -sS -X POST \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/statuses/${HEAD_SHA}" \
            -d '{"state":"pending","context":"gate","description":"gate running"}'

      - name: Evaluate approvals (pass iff ≥1 active approval)
        id: eval
        run: |
          # Fetch all reviews; keep only each user's latest review state; count APPROVED
          data="$(curl -sS -H "Authorization: Bearer ${{ github.token }}" \
                        -H "Accept: application/vnd.github+json" \
                        -H "X-GitHub-Api-Version: 2022-11-28" \
                        "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/reviews")"
          approvals=$(echo "$data" | jq '[ group_by(.user.login) | .[] | last | select(.state=="APPROVED") ] | length')
          echo "approvals=$approvals"
          if [ "${approvals:-0}" -ge 1 ]; then
            echo "OK: ${approvals} approval(s)."
          else
            echo "Need at least one active approval." >&2
            exit 1
          fi

      - name: gate status → conclude
        if: ${{ always() }}
        env:
          JOB_STATUS: ${{ job.status }}
        run: |
          if [ "$JOB_STATUS" = "success" ]; then
            STATE=success; DESC="gate passed"
          else
            STATE=failure; DESC="gate failed"
          fi
          curl --fail-with-body -sS -X POST \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/statuses/${HEAD_SHA}" \
            -d "{\"state\":\"$STATE\",\"context\":\"gate\",\"description\":\"$DESC\"}"
