name: chimera-gate
on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
permissions:
  contents: read
  statuses: write
jobs:
  gate:
    name: gate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Emit legacy commit status (success)
        uses: actions/github-script@v7
        with:
          script: |
            const isPR = context.eventName === 'pull_request';
            const sha = isPR ? context.payload.pull_request.head.sha : context.sha;
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            // Smoke pass; adjust logic later as needed
            await github.rest.repos.createCommitStatus({
              owner, repo, sha,
              state: 'success',
              context: 'chimera-gate / gate',
              description: 'Gate: smoke OK',
              target_url: `${context.serverUrl}/${owner}/${repo}/actions/runs/${context.runId}`
            });