name: chimera-gate

on:
  pull_request:
    branches: [ main ]

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Optional debug so you can see what the runner sees
      - name: Debug artifacts tree
        run: |
          echo "::group::Artifacts tree"
          (find artifacts -maxdepth 3 -type f -print || true)
          echo "::endgroup::"

      - name: Find latest gate.decision.json
        id: find
        run: |
          set -euo pipefail
          file="$(find artifacts -type f -name gate.decision.json 2>/dev/null | sort | tail -n 1 || true)"
          if [ -z "${file}" ]; then
            echo "No gate.decision.json found." >&2
            exit 1
          fi
          echo "file=${file}" >> "$GITHUB_OUTPUT"

      - name: Verify decision == approve
        run: |
          sudo apt-get update -qq && sudo apt-get install -y -qq jq
          decision=$(jq -r '.decision' "${{ steps.find.outputs.file }}")
          echo "Gate decision: ${decision}"
          test "${decision}" = "approve"
