name: chimera-gate

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: chimera-gate-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  statuses: write

defaults:
  run:
    shell: bash

jobs:
  gate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      # Use PR head when present; fall back to the current commit SHA otherwise
      HEAD_SHA: ${{ github.event.pull_request.head.sha || github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: gate status → pending
        if: ${{ always() }}
        run: |
          curl --fail-with-body -sS -X POST \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/statuses/${HEAD_SHA}" \
            -d '{"state":"pending","context":"gate","description":"gate running"}'

      # ── YOUR REAL VALIDATION GOES HERE ─────────────────────────────────────────
      - name: Run gate validation
        run: |
          echo "TODO: implement your actual gate checks."
          # exit 1  # uncomment to simulate a failing gate
      # ───────────────────────────────────────────────────────────────────────────

      - name: gate status → conclude
        if: ${{ always() }}
        env:
          JOB_STATUS: ${{ job.status }}
        run: |
          if [ "$JOB_STATUS" = "success" ]; then
            STATE=success; DESC="gate passed"
          else
            STATE=failure; DESC="gate failed"
          fi
          curl --fail-with-body -sS -X POST \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/statuses/${HEAD_SHA}" \
            -d "{\"state\":\"$STATE\",\"context\":\"gate\",\"description\":\"$DESC\"}"
