name: ChimeraHydra Gate - Failure Mirror
on:
  workflow_run:
    types: [completed]
jobs:
  mirror:
    if: ${{ github.event.workflow_run.path == '.github/workflows/chimerahydra-gate.yml' && github.event.workflow_run.conclusion != 'success' }}
    permissions:
      contents: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Post legacy failure status to PR head
        uses: actions/github-script@v7
        with:
          script: |
            const sha = context.payload.workflow_run.head_sha;
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha,
              state: 'failure',
              context: 'chimera-gate / gate',
              description: 'Gate rejected',
              target_url: context.payload.workflow_run.html_url
            });
